### ISSUE TITLE
Make hyperlinks purple

### ISSUE THREAD

**Issue by monkeyjonjon** [onmagnoliasquare/website#131]
### Description

Hyperlinks should be purple instead of green.
![image](https://github.com/user-attachments/assets/46376e47-2734-4678-ab95-7095ebd1ad22)

**Comment by n30w** [comment]
@monkeyjonjon I trust you can figure this one out. It's a basic exercise in CSS.

Here are some hints:

- Checkout the very bottom of `onmagnoliasquare.css`. By the way, to open a file quickly in VSCode, do `ctrl-p` and type the name of the file.
