### ISSUE TITLE
Committee rendering on the frontend

### ISSUE THREAD

**Issue by n30w** [onmagnoliasquare/website#171]
### Description

In the bio section, show a member's committee. Perhaps we can also extend this into the about section, where we can organize everyone by their committee.

**Comment by monkeyjonjon** [comment]
![image](https://github.com/user-attachments/assets/5488f928-13dd-4168-82b0-5182a812e3b4)
@n30w

**Comment by n30w** [comment]
@monkeyjonjon I'm gonna merge some changes to the Sanity fetching API tonight. Before we merge this issue you'll have to update your query to fit the new features I created... Sorry 😭

**Comment by monkeyjonjon** [comment]
@n30w Oh OK, lemme know if you need help
